<a href="https://colab.research.google.com/github/LeMeASh/Python/blob/main/PythonSec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.arange(5).reshape(1,5)
x

array([[0, 1, 2, 3, 4]])

In [ ]:
x + 5

array([[5, 6, 7, 8, 9]])

In [ ]:
y = np.arange(20).reshape(5,4)

y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
x + y

ValueError: operands could not be broadcast together with shapes (1,5) (5,4) 

# Broadcasting rule
Arrays can broadcast against each other only if either of their corresponding axis length match or if one of the arrays has axis length of 1

In [ ]:
a = np.arange(48).reshape((6,1,8))
b = np.arange(32).reshape((1,4,8))

In [ ]:
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47]]])

In [ ]:
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]])

In [ ]:
c=a+b
c

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70,

In [ ]:
a.shape

(6, 1, 8)

In [ ]:
b.shape

(1, 4, 8)

In [ ]:
c.shape

(6, 4, 8)

In [ ]:
a1= np.arange(3).reshape(1,3)
a1

array([[0, 1, 2]])

In [ ]:
a1.shape

(1, 3)

In [ ]:
a2= np.arange(9).reshape(3,3)
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a3=a1 + a2
a3

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
x = np.arange(1, 100, 10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
sq = np.square(x)
sq

array([   1,  121,  441,  961, 1681, 2601, 3721, 5041, 6561, 8281],
      dtype=int32)

In [ ]:
exp = np.exp(x)
exp

array([2.71828183e+00, 5.98741417e+04, 1.31881573e+09, 2.90488497e+13,
       6.39843494e+17, 1.40934908e+22, 3.10429794e+26, 6.83767123e+30,
       1.50609731e+35, 3.31740010e+39])

In [ ]:
np.sin(x)

array([ 0.84147098, -0.99999021,  0.83665564, -0.40403765, -0.15862267,
        0.67022918, -0.96611777,  0.95105465, -0.62988799,  0.10598751])

In [ ]:
y = np.linspace(1, 10, 20)
y

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.ceil(y)

array([ 1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.,
        8.,  8.,  9.,  9., 10., 10., 10.])

In [ ]:
np.floor(y)

array([ 1.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
        7.,  7.,  8.,  8.,  9.,  9., 10.])

Binary universal functions

In [ ]:
sub1_scores = np.random.randint(20, 100, size=(10))
sub2_scores = np.random.randint(20, 100, size=(10))

print(sub1_scores)
print(sub2_scores)

[57 64 29 65 40 95 23 69 90 27]
[78 42 75 44 39 72 60 21 87 21]


In [ ]:
total_score = np.add(sub1_scores, sub2_scores)
total_score

array([135, 106, 104, 109,  79, 167,  83,  90, 177,  48])

In [ ]:
best_score_out_of_two = np.maximum(sub1_scores, sub2_scores)

best_score_out_of_two

array([78, 64, 75, 65, 40, 95, 60, 69, 90, 27])

In [ ]:
base_arr = np.arange(1, 10)
power_arr = np.arange(1, 10)
ans = np.power(base_arr, power_arr)
ans

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489], dtype=int32)

Making a non-vectorized function vectorized

In [ ]:
from math import factorial

a = 5
factorial(a)

120

In [ ]:
x = np.arange(1, 6)
factorial(x)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
vec_fact = np.vectorize(factorial)

print(x)
print(vec_fact(x))

[1 2 3 4 5]
[  1   2   6  24 120]
