<a href="https://colab.research.google.com/github/LeMeASh/Python/blob/main/PythonFirst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

For auto completion and information, use Tab or shift+tab 

In [ ]:
class student :
    college= "RIT"
    def __init__(self, fname, lname, age):
        self.fname=fname
        self.lname=lname
        self.age=age
    def percentage(self,sub1,sub2,sub3):
        total=sub1+sub2+sub3;
        print(total/3)
        
class inherit(student):
    pass

    

In [ ]:
st1 = student("ash","king",17)


In [ ]:
print(f"{st1.fname} is {st1.age} years old")

ash is 17 years old


In [ ]:
st1.percentage(96, 92, 88)

92.0


In [ ]:
st2 = inherit("loki","thor", 99)

In [ ]:
print(f"{st2.fname} is {st2.age} years old")

loki is 99 years old


In [ ]:
st2.percentage(96, 92, 88)

92.0


In [ ]:
st1.college

'RIT'

In [ ]:
fruits = ["Apple","banana","Pinapple","kiwi"]
copycat = [ item for item in fruits]

In [ ]:
copycat

['Apple', 'banana', 'Pinapple', 'kiwi']

In [ ]:
onlyA = [item+item for item in fruits if "a" in item]

In [ ]:
onlyA

['bananabanana', 'PinapplePinapple']

In [ ]:
import math

In [ ]:
math.log(2)

0.6931471805599453

In [ ]:
math.log(10)

2.302585092994046

In [ ]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [ ]:
with open("sample.txt", 'w') as f:
    f.write("Hello World!!!!!!!!!")

In [ ]:
with open("sample.txt", 'r') as f:
    print(f.read())

Hello World!!!!!!!!!


In [ ]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    comb(n, k, /)
        Number of ways to choose k items from n items without repetition and without order

Numpy to work with multidimensional array

In [ ]:
import numpy as np
import math
arr= np.array([1,3,4,5,6])

In [ ]:
division = (arr/3)

In [ ]:
print(division)

[0.33333333 1.         1.33333333 1.66666667 2.        ]


In [ ]:
division.dtype


dtype('float64')

In [ ]:
type(division)

numpy.ndarray

np.zeros

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.linspace is used to create evenly distanced values between the range given. Here it will create evenly distanced 10 values start from 1 to 100.

In [ ]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

//Converting array of float into integer

In [ ]:
a_float= np.array([2,5.6,7.9,9],dtype=float)
a_float

array([2. , 5.6, 7.9, 9. ])

In [ ]:
a_int= a_float.astype(int)

In [ ]:
a_int

array([2, 5, 7, 9])

In [ ]:
ar= np.zeros((3, 3))

In [ ]:
ar.ndim

2

In [ ]:
ar

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ar.size

9

In [ ]:
arr =np.arange(1,20,2)

In [ ]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr[::-1]

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [ ]:
arr[::2]

array([ 1,  5,  9, 13, 17])

In [ ]:
arr[3:8]

array([ 7,  9, 11, 13, 15])

In [ ]:
arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[1][1]

5

In [ ]:
arr_2d[1,1]

5

In [ ]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr_2d[:,-1]

array([3, 6, 9])

In [ ]:
arr_2d[:,:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr>9

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr>9]

array([11, 13, 15, 17, 19])

In [ ]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d>=5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr_2d[arr_2d>=5]

array([5, 6, 7, 8, 9])

In [ ]:
arr_2d[(arr_2d>3) & (arr_2d <7)]

array([4, 5, 6])

In [ ]:
arr_2d[1:2]

array([[4, 5, 6]])

In [ ]:
arr1= np.array([1,2,3])

In [ ]:
arr2= np.array([1,2,3])

In [ ]:
arr1*arr2

array([1, 4, 9])

In [ ]:
ar1= np.arange(9).reshape(3,3)
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
ar2=np.arange(9).reshape(1,3,3)

In [ ]:
ar2

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [ ]:
ar3=np.arange(9).reshape(3,1,3)

In [ ]:
ar3

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [ ]:
ar3.shape

(3, 1, 3)

In [ ]:
ar3[2]

array([[6, 7, 8]])

In [ ]:
ar3.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
ar3=np.arange(9).reshape(3,3,order = "F")

This will create the column major order while creating rhe array

In [ ]:
ar3

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
ar3=np.arange(20).reshape(2,10)

In [ ]:
ar3.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
ar3.shape

(2, 10)

In [ ]:
ar3.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
ar3.reshape(-1,5).shape

(4, 5)

# It will automatically add value so that it will fit array perfectly if we dont know what dimensions should be

In [ ]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
ar3.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [ ]:
ar3.T

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

# Flattening an array 
Means to convert higher dimensional array into 1d array

In [ ]:
ar3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
    ar3.shape

(2, 10)

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr2

array([1, 2, 3])

In [ ]:
np.concatenate([arr1,arr2])

array([1, 2, 3, 1, 2, 3])

In [ ]:
arr1= np.arange(6).reshape(2,3)

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2= np.arange(6,12).reshape(2,3)

In [ ]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate([arr1,arr2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# random number generator 

In [ ]:
import numpy as np

normal_data = np.random.normal(size=(5,3))
normal_data

array([[ 1.35281515,  0.30570697,  0.37012004],
       [-0.77680231, -0.17485106, -1.02091873],
       [-0.20526355,  1.1987457 , -0.70366849],
       [ 0.7484218 , -1.60708567,  0.68699543],
       [-0.65798834, -0.32548229, -2.54308267]])

Compare the speed with python's builtin random module

In [ ]:
from random import normalvariate

n = 10000
%timeit [normalvariate(0,1) for _ in range(n)]

11.8 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit np.random.normal(size=n)

370 µs ± 25.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Use seed when we want perticular random vars even if we run it again and again

In [ ]:
np.random.seed(5)
np.random.randint(1, 10, size=(10))

array([4, 7, 7, 1, 9, 5, 8, 1, 1, 8])

In [ ]:
np.random.randint(1, 10, size=(10))

array([2, 6, 8, 1, 2, 5, 7, 3, 2, 3])

In [ ]:
np.random.seed(5)
np.random.randint(1, 10, size=(10))

array([4, 7, 7, 1, 9, 5, 8, 1, 1, 8])

In [ ]:
arr = [5,6,2,1,0]
np.random.shuffle(arr)
arr

[2, 6, 0, 1, 5]

In [ ]:
np.random.binomial(1, 0.5, size=(10))

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 0])

In [ ]:


np.random.uniform(size=(10))



array([0.25358821, 0.32756395, 0.1441643 , 0.16561286, 0.96393053,
       0.96022672, 0.18841466, 0.02430656, 0.20455555, 0.69984361])